Repository waves-of-hope/resource-center, pull requests merged in 2020-10, with the labels that each got.

#12 Refactored templates and renamed functional test classes
  resource_center/tests.py
  resources/templates/resources/book-card.html
  resources/templates/resources/book.html
  resources/templates/resources/meta.html
  resources/templates/resources/resource_list.html
  resources/templates/resources/video-card.html
  resources/templates/resources/video.html
  templates/base.html
  templates/footer.html
  templates/index.html
  templates/navbar.html
Labels: bug fix, enhancement

#13 Added pagination
  resource_center/tests.py
  resources/tests/test_views.py
  resources/views.py
  templates/base.html
  templates/pagination.html
Labels: enhancement

#14 Modified the service and ALLOWED_HOSTS setting in app.yaml.py
  app.yaml.py
Labels: enhancement

#15 Finished developing book and video list and detail pages, closes #3
  .github/workflows/prod.yaml
  accounts/models.py
  accounts/templates/accounts/profile.html
  accounts/tests/test_models.py
  accounts/tests/test_urls.py
  accounts/tests/test_views.py
  accounts/urls.py
  app.yaml.py
  requirements.txt
  resource_center/settings.py
  resource_center/tests.py
  resource_center/urls.py
  resources/admin.py
  resources/migrations/0001_initial.py
  resources/models.py
  resources/templates/resources/book-card.html
  resources/templates/resources/book.html
  resources/templates/resources/meta.html
  resources/templates/resources/resource_list.html
  resources/templates/resources/video-card.html
  resources/templates/resources/video.html
  resources/tests/test_models.py
  resources/tests/test_urls.py
  resources/tests/test_views.py
  resources/urls.py
  resources/views.py
  static/css/main.css
  staticfiles/css/main.css
  templates/base.html
  templates/footer.html
  templates/index.html
  templates/navbar.html
  templates/pagination.html
  test_files/documents/book.pdf
  test_files/images/book-cover.jpg
  test_files/images/book-cover.png
  test_files/images/default.png
  test_files/images/user.png
Labels: enhancement

#16 Modified gitignore and project settings
  .gitignore
  resource_center/settings.py
Labels: bug fix

#17 Updated envvars in production workflow
  .github/workflows/prod.yaml
Labels: bug fix

#18 Updated envvars in app.yaml.py
  app.yaml.py
Labels: bug fix

#19 Updated envvars in app.yaml.py
  app.yaml.py
Labels: bug fix
